dataset:
  name: pl
  path: /data/pdbbind_pocket10
  split: /data/split_by_name.pt

model:
  checkpoint: ./checkpoints/pretrained.pt
  hidden_channels: 256
  random_alpha: False

sample:
  seed: 2024
  num_samples: 100
  num_retry: 5
  max_steps: 12
  batch_size: 10
  num_workers: 4
  n_samples: 5
